/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE productsBaseService PLEASE EDIT ../products.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Products } from '../../domain/mamamboga_db/products';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Products.service.ts
 */

/*
 * SCHEMA DB Products
 *
	{
		Name: {
			type: 'String',
			required : true
		},
		Price: {
			type: 'Number'
		},
		Quantity: {
			type: 'Number'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
	}
 *
 */
@Injectable()
export class ProductsBaseService {

    contextUrl: string = environment.endpoint + '/products';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * ProductsService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Products): Observable<Products> {
        return this.http
            .post<Products>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * ProductsService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * ProductsService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id 
    *
    */
    get(id: string): Observable<Products> {
        return this.http
            .get<Products>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * ProductsService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Products[]> {
        return this.http
            .get<Products[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * ProductsService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Products): Observable<Products> {
        return this.http
            .post<Products>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
